domain: webteam.canonical.com

image: prod-comms.docker-registry.canonical.com/webteam.canonical.com

env:
  - name: SENTRY_DSN
    value: https://ac1f05d48419453ab98e9af52d0da6ae@sentry.is.canonical.com//35

  - name: RELEASES_GITHUB_TOKEN
    secretKeyRef:
      key: releases-github-token
      name: github-api

memoryLimit: 128Mi

# Overrides for production
production:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
