domain: webteam.canonical.com

image: prod-comms.docker-registry.canonical.com/webteam.canonical.com

env:
  - name: SENTRY_DSN
    value: https://ac1f05d48419453ab98e9af52d0da6ae@sentry.is.canonical.com//35

  - name: RELEASES_GITHUB_TOKEN
    secretKeyRef:
      key: releases-github-token
      name: github-api

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: discourse_api_key
      name: canonical-discourse

  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: discourse-api-username
      name: canonical-discourse

  - name: PRIVATE_KEY_ID
    secretKeyRef:
      key: private-key-id
      name: specs-canonical-com

  - name: PRIVATE_KEY
    secretKeyRef:
      key: private-key
      name: specs-canonical-com

memoryLimit: 128Mi

# Overrides for production
production:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

demo:
  env:
    - name: OPENID_LAUNCHPAD_TEAM
      value: canonical-content-people
