domain: releases.demo.haus

image: prod-comms.docker-registry.canonical.com/releases.demo.haus

env:
  - name: SENTRY_DSN
    value: https://ac1f05d48419453ab98e9af52d0da6ae@sentry.is.canonical.com//35

useProxy: false

memoryLimit: 128Mi

noTls: true

# Overrides for production
production:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
